[package]
edition = "2021"
name = "gtkwgpuarea"
version = "0.1.0"

[dependencies]
epoxy = "0.1"
gtk4 = { version = "0.9.0", features = ["v4_14"] }
libloading = "0.8.5"
wgpu = "22.0.0"
wgpu-hal = "22.0.0"
wgpu-types = "22.0.0"
